# Generated by Django 3.0.2 on 2020-01-25 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=200)),
                ('Customer_address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
